name: DADuels
version: ${project.version}
main: io.github.sirnik.daduels.DADuels
api-version: 1.13
authors: [sirNik]
description: Organized duelling plugin
website: https://sirnik.dev
commands:
  daduels:
    description: base command for daduels
